/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});


Ext.application({
    models: [
        'gmo.security.segsistema.mdsistema',
        'gmo.security.segmenu.mdsegmenu',
        'gmo.security.segmenu.mdsegmenucarpeta',
        'gmo.security.segmenu.mdsegmenuorden',
        'gmo.security.segplantilla.mdsegplantilla',
        'gmo.security.segmenuopcion.mdsegmenuopcion',
        'gmo.security.segmenuopcion.mdsegmenuopcionorden'
    ],
    stores: [
        'gmo.security.segsistema.stsegsistema',
        'gmo.security.segmenu.stsegmenu',
        'gmo.security.segmenu.stsegmenucarpeta',
        'gmo.security.segmenu.stsegmenuorden',
        'gmo.security.segplantilla.stsegplantilla',
        'gmo.security.segmenuopcion.stsegmenuopcion',
        'gmo.security.segmenu.stsegmenutipo',
        'gmo.security.segmenuopcion.stsegmenuopcionorden'
    ],
    views: [
        'gmo.security.segsistema.vpmain',
        'gmo.security.segsistema.winMtto',
        'gmo.security.segmenuopcion.winMtto',
        'gmo.security.segmenu.winMtto'
    ],
    appFolder: '../../../seg/app/seg',
    appProperty: 'seg',
    controllers: [
        'gmo.security.segsistema.vpMain',
        'gmo.security.segmenu.crtMtto',
        'gmo.security.segmenuopcion.ctrMtto'
    ],
    name: 'seg',

    launch: function() {
        Ext.create('seg.view.gmo.security.segsistema.vpmain', {renderTo: Ext.getBody()});
    }

});
